---
title: "Presentation Title Here"
author: "Your Name Here"
date: "`r Sys.Date()`"
output:
  ioslides_presentation: default
  powerpoint_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Instructions
- You will be required to present the results of your final project
- The structure of the presentation must follow the structure of the final project
  - For more information [visit this link](https://drfurtado.github.io/isk-ancillary/projects/project1.html#33_Written_report)
- I've created this presentation template to help you getting started
- To get started, download this template as PowerPoint by [clicking here](pres-template.pptx)
- Once done, save your Presentation as PDF and submit it via Canvas.
- 


## Background
- Main points from the 3 articles you found on your topic

## Method - Participants
- help found here --> https://bit.ly/3C46nbw

## Method - Design
- help found here --> https://bit.ly/3iAR2rQ
- more help found here --> https://bit.ly/37TZdgE

## Method - Statistical Analysis
- help found here --> https://bit.ly/31skJ5I

## Method - Materials
- help found here --> https://bit.ly/3iAR2rQ

## Method - Procedures
- help found here --> https://bit.ly/3iAR2rQ

## Results
- help found here --> https://bit.ly/3Lg9qT5

## References
- help found here --> https://bit.ly/3tHqIm7

## Questions